baseurl = "https://sanjeev.github.io"
#baseurl = "localhost:1313"
languageCode = "en-us"
title = "SM"
metaDataFormat = "yaml"
newContentEditor = "vim"
theme = "manifest"
SectionPagesMenu = "main"

[taxonomies]
  tag = "tags"
#  category = "categories"

[params]
  author = "smalalur-gh"
  title = "Sanjeev Malalur, PhD"
  subtitle = ""
  name = "Sanjeev Malalur"
  email = "sanjeev.malalur@gmail.com"
  UseHighlightJS = true

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

[menu]
  # [[menu.main]]
    # identifier = "resume"
    # name = "resume"
    # url = "/resume.pdf"
    # weight = 4

  #[[menu.main]]
    #identifier = "posts"
    #name = "Writings"
    #url = "/posts/"
    #weight = 3
